#!url=https://raw.githubusercontent.com/iexam/ad/refs/heads/main/iexamad.module
#!name=!!屏蔽各种广告
#!desc=自定义屏蔽各种广告
#!author=123456


[Rule]
#zhihu
DOMAIN-SUFFIX,ads.zhihu.com,REJECT-DROP

#QQMail
DOMAIN-SUFFIX,mma.qq.com,REJECT-DROP
DOMAIN-SUFFIX,tcd.qq.com,REJECT-DROP
DOMAIN-SUFFIX,e.qq.com,REJECT-DROP
DOMAIN-SUFFIX,qzonestyle.gtimg.cn,REJECT-DROP
DOMAIN-SUFFIX,admail.qq.com,REJECT-DROP

#百事AA记账
DOMAIN-SUFFIX,p2-ad.adukwai.com,REJECT-DROP
DOMAIN-SUFFIX,p3-ad.adukwai.com,REJECT-DROP
DOMAIN-SUFFIX,p4-ad.adukwai.com,REJECT-DROP
DOMAIN-SUFFIX,p5-ad.adukwai.com,REJECT-DROP
DOMAIN-SUFFIX,p6-ad.adukwai.com,REJECT-DROP

#12306
DOMAIN-SUFFIX,ad.12306.cn,REJECT-DROP
