#!url=https://raw.githubusercontent.com/iexam/ad/refs/heads/main/iexamad.module
#!name=屏蔽各种广告
#!desc=屏蔽各种广告
#!author=123456


[Rule]
#zhihu
DOMAIN-SUFFIX,apm.zhihu.com,REJECT-DROP
DOMAIN-SUFFIX,sugar.zhihu.com,REJECT-DROP
DOMAIN-SUFFIX,event.zhihu.com,REJECT-DROP
DOMAIN-SUFFIX,ad-account.zhihu.com,REJECT-DROP
DOMAIN-SUFFIX,api.zhihu.com,REJECT-DROP
DOMAIN-SUFFIX,ads.zhihu.com,REJECT-DROP

#QQMail
DOMAIN-SUFFIX,mma.qq.com,REJECT-DROP
DOMAIN-SUFFIX,tcd.qq.com,REJECT-DROP
DOMAIN-SUFFIX,e.qq.com,REJECT-DROP
DOMAIN-SUFFIX,qzonestyle.gtimg.cn,REJECT-DROP
DOMAIN-SUFFIX,admail.qq.com,REJECT-DROP

#
